// chip content
NUTOOL_CLOCK.g_cfg_chips = [
    // KM1M0D0F_100
    { name: "KM1M0DF02N/K", pkg: "LQFP100_D0x" },
    // KM1M0D0F_80
    { name: "KM1M0DF03N/K", pkg: "LQFP80_D0x" },
    // KM1M0D1F
    { name: "KM1M0DF13N/K", pkg: "LQFP80_D1x" },
    // KM1M0D0F_64
    { name: "KM1M0DF04N/K", pkg: "TQFP64_D0x" }
];

NUTOOL_CLOCK.g_register_map = [];
NUTOOL_CLOCK.g_register_map.CKCTR = ['LXODRV:11', 'HXODRV:9', 'PWRDWN:6', 'LXOEN:3', 'HXOEN:1', 'HRCEN:0'];
NUTOOL_CLOCK.g_register_map.CKSEL = ['HPCLKSEL:5-4', 'LPCKSEL:3', 'SYSCLKSEL:2-0'];
NUTOOL_CLOCK.g_register_map.CPUCKCTR = ['SYSDIV:6-4', 'CPUCKDIV:2-0'];
NUTOOL_CLOCK.g_register_map.PLLCTR1 = ['PLLSTART:1', 'NPLLEN:0'];
NUTOOL_CLOCK.g_register_map.PLLCTR2 = ['NRSET_PLL:15', 'PLLODIV:12', 'PLLISEL:11', 'PLLIDIV:10-8', 'MUL_PLL:7-0'];
NUTOOL_CLOCK.g_register_map.CKSTAT = ['LPCLKST:25-24', 'HPCLKST:18-16', 'SYSCLKST:12-8', 'LRCOK:2', 'HRCOK:0'];
NUTOOL_CLOCK.g_register_map.DSLEEPMD = [];
//NUTOOL_CLOCK.g_register_map.DSLEEPMD = ['PWRDWN:6', 'SYSEN:5', 'PLLEN:4', 'LXOEN:3', 'LRCEN:2', 'HXOEN:1', 'HRCEN:0'];
NUTOOL_CLOCK.g_register_map.PERICKEN0 = ['PECKEN11:11', 'PECKEN10:10', 'PECKEN9:9', 'PECKEN8:8', 'PECKEN7:7', 'PECKEN6:6', 'PECKEN5:5', 'PECKEN4:4', 'PECKEN3:3', 'PECKEN2:2', 'PECKEN1:1', 'PECKEN0:0'];
NUTOOL_CLOCK.g_register_map.PERICKEN1 = ['PECKEN11:11', 'PECKEN10:10', 'PECKEN9:9', 'PECKEN8:8', 'PECKEN7:7', 'PECKEN6:6', 'PECKEN5:5', 'PECKEN4:4', 'PECKEN3:3', 'PECKEN2:2', 'PECKEN1:1', 'PECKEN0:0'];

// Be careful. The order of g_register_map_default will affect the result in the generated code.
NUTOOL_CLOCK.g_register_map_default = [];
NUTOOL_CLOCK.g_register_map_default.CKCTR     = '0xA53C0005';
NUTOOL_CLOCK.g_register_map_default.CKSEL     = '0xA53C0000';
NUTOOL_CLOCK.g_register_map_default.CPUCKCTR  = '0xA53C0000';
NUTOOL_CLOCK.g_register_map_default.PLLCTR1   = '0xA53C0001';
NUTOOL_CLOCK.g_register_map_default.PLLCTR2   = '0xA53C0020';
NUTOOL_CLOCK.g_register_map_default.CKSTAT    = '0xA53C0000';
NUTOOL_CLOCK.g_register_map_default.DSLEEPMD  = '0xA53C0000';
NUTOOL_CLOCK.g_register_map_default.PERICKEN0 = '0xA53C0000';
NUTOOL_CLOCK.g_register_map_default.PERICKEN1 = '0xA53C0000';

NUTOOL_CLOCK.g_register_map_description = [];
NUTOOL_CLOCK.g_register_map_description.CKCTR     = '0x40001000';
NUTOOL_CLOCK.g_register_map_description.CKSEL     = '0x40001004';
NUTOOL_CLOCK.g_register_map_description.CPUCKCTR  = '0x40001008';
NUTOOL_CLOCK.g_register_map_description.PLLCTR1   = '0x4000100C';
NUTOOL_CLOCK.g_register_map_description.PLLCTR2   = '0x40001010';
NUTOOL_CLOCK.g_register_map_description.CKSTAT    = '0x40001014';
NUTOOL_CLOCK.g_register_map_description.DSLEEPMD  = '0x40001020';
NUTOOL_CLOCK.g_register_map_description.PERICKEN0 = '0x40001024';
NUTOOL_CLOCK.g_register_map_description.PERICKEN1 = '0x40001028';

NUTOOL_CLOCK.g_CLKSEL = [];
NUTOOL_CLOCK.g_CLKSEL.PLLISEL = ['HRCCLK:0', 'HXOCLK:1'];
NUTOOL_CLOCK.g_CLKSEL.PLLIDIV = ['PLLISEL:0', 'PLLISEL/2:1', 'PLLISEL/3:2', 'PLLISEL/4:3', 'PLLISEL/5:4..7'];
NUTOOL_CLOCK.g_CLKSEL.MUL_PLL = ['PLL_IN*32:32', 'PLL_IN*40:40', 'PLL_IN*64:64'];
NUTOOL_CLOCK.g_CLKSEL.PLLODIV = ['PLL_OUT/4:0', 'PLL_OUT/6:1'];
NUTOOL_CLOCK.g_CLKSEL.HPCLKSEL = ['HRCCLK:0', 'HXOCLK:1', 'PLLCLK:2'];
NUTOOL_CLOCK.g_CLKSEL.SYSCLKSEL =['HRCCLK:0', 'HXOCLK:1', 'LRCCLK:2', 'LXOCLK:3', 'PLLCLK:4'];
NUTOOL_CLOCK.g_CLKSEL.LPCKSEL = ['LRCCLK:0', 'LXOCLK:1'];
NUTOOL_CLOCK.g_CLKSEL.SYSDIV = ['BASECLK:0', 'BASECLK/2:1', 'BASECLK/4:2', 'BASECLK/8:3', 'BASECLK/16:4'];
NUTOOL_CLOCK.g_CLKSEL.CPUCKDIV = ['SYSCLK:0', 'SYSCLK/2:1', 'SYSCLK/4:2', 'SYSCLK/8:3', 'SYSCLK/16:4', 'SYSCLK/32:5', 'SYSCLK/64:6', 'SYSCLK/128:7'];
NUTOOL_CLOCK.g_CLKSEL_EXTENDED = [];

NUTOOL_CLOCK.g_Module = [];
NUTOOL_CLOCK.g_Module.ADC = ['SYSCLK', 'PERICKEN1.PECKEN2', 'none', 'ADC_MODULE'];
NUTOOL_CLOCK.g_Module.BUZ = ['SYSCLK', 'PERICKEN0.PECKEN7', 'none', 'BUZ_MODULE'];
NUTOOL_CLOCK.g_Module.CRC = ['SYSCLK', 'PERICKEN1.PECKEN1', 'none', 'CRC_MODULE'];
NUTOOL_CLOCK.g_Module.DMA0 = ['SYSCLK', 'PERICKEN0.PECKEN10', 'none', 'DMA0_MODULE'];
NUTOOL_CLOCK.g_Module.DMA1 = ['SYSCLK', 'PERICKEN0.PECKEN11', 'none', 'DMA1_MODULE'];
NUTOOL_CLOCK.g_Module.I2C_6 = ['SYSCLK', 'PERICKEN1.PECKEN9', 'none', 'SIF6_MODULE'];
NUTOOL_CLOCK.g_Module.I2C_7 = ['SYSCLK', 'PERICKEN1.PECKEN10', 'none', 'SIF7_MODULE'];
NUTOOL_CLOCK.g_Module.I2C_8 = ['SYSCLK', 'PERICKEN1.PECKEN11', 'none', 'SIF8_MODULE'];
NUTOOL_CLOCK.g_Module.LIN = ['SYSCLK', 'PERICKEN1.PECKEN3', 'none', 'SIF0_MODULE'];
NUTOOL_CLOCK.g_Module.NF = ['SYSCLK', 'PERICKEN1.PECKEN0', 'none', 'NF_MODULE'];
NUTOOL_CLOCK.g_Module.PWM = ['SYSCLK', 'PERICKEN0.PECKEN9', 'none', 'PWM_MODULE'];
NUTOOL_CLOCK.g_Module.RTC = ['SYSCLK', 'PERICKEN0.PECKEN8', 'none', 'RTC_MODULE'];
NUTOOL_CLOCK.g_Module.SIF0 = ['SYSCLK', 'PERICKEN1.PECKEN3', 'none', 'SIF0_MODULE'];
NUTOOL_CLOCK.g_Module.SIF1 = ['SYSCLK', 'PERICKEN1.PECKEN4', 'none', 'SIF1_MODULE'];
NUTOOL_CLOCK.g_Module.SIF2 = ['SYSCLK', 'PERICKEN1.PECKEN5', 'none', 'SIF2_MODULE'];
NUTOOL_CLOCK.g_Module.SIF3 = ['SYSCLK', 'PERICKEN1.PECKEN6', 'none', 'SIF3_MODULE'];
NUTOOL_CLOCK.g_Module.SIF4 = ['SYSCLK', 'PERICKEN1.PECKEN7', 'none', 'SIF4_MODULE'];
NUTOOL_CLOCK.g_Module.SIF5 = ['SYSCLK', 'PERICKEN1.PECKEN8', 'none', 'SIF5_MODULE'];
NUTOOL_CLOCK.g_Module.SIF6 = ['SYSCLK', 'PERICKEN1.PECKEN9', 'none', 'SIF6_MODULE'];
NUTOOL_CLOCK.g_Module.SIF7 = ['SYSCLK', 'PERICKEN1.PECKEN10', 'none', 'SIF7_MODULE'];
NUTOOL_CLOCK.g_Module.SIF8 = ['SYSCLK', 'PERICKEN1.PECKEN11', 'none', 'SIF8_MODULE'];
NUTOOL_CLOCK.g_Module.TIMER_8BIT = ['SYSCLK', 'PERICKEN0.PECKEN0', 'none', 'TIMER_8BIT_MODULE'];
NUTOOL_CLOCK.g_Module.TIMER_8BITL = ['SYSCLK', 'PERICKEN0.PECKEN1', 'none', 'TIMER_8BITL_MODULE'];
NUTOOL_CLOCK.g_Module.TIMER11_12 = ['SYSCLK', 'PERICKEN0.PECKEN4', 'none', 'TIMER11_12_MODULE'];
NUTOOL_CLOCK.g_Module.TIMER13_14 = ['SYSCLK', 'PERICKEN0.PECKEN5', 'none', 'TIMER13_14_MODULE'];
NUTOOL_CLOCK.g_Module.TIMER15 = ['SYSCLK', 'PERICKEN0.PECKEN6', 'none', 'TIMER15_MODULE'];
NUTOOL_CLOCK.g_Module.TIMER7_8 = ['SYSCLK', 'PERICKEN0.PECKEN2', 'none', 'TIMER7_8_MODULE'];
NUTOOL_CLOCK.g_Module.TIMER9_10 = ['SYSCLK', 'PERICKEN0.PECKEN3', 'none', 'TIMER9_10_MODULE'];
NUTOOL_CLOCK.g_Module.UART_0 = ['SYSCLK', 'PERICKEN1.PECKEN3', 'none', 'SIF0_MODULE'];
NUTOOL_CLOCK.g_Module.UART_1 = ['SYSCLK', 'PERICKEN1.PECKEN4', 'none', 'SIF1_MODULE'];
NUTOOL_CLOCK.g_Module.UART_2 = ['SYSCLK', 'PERICKEN1.PECKEN5', 'none', 'SIF2_MODULE'];
NUTOOL_CLOCK.g_Module.UART_3 = ['SYSCLK', 'PERICKEN1.PECKEN6', 'none', 'SIF3_MODULE'];
NUTOOL_CLOCK.g_Module.UART_4 = ['SYSCLK', 'PERICKEN1.PECKEN7', 'none', 'SIF4_MODULE'];
NUTOOL_CLOCK.g_Module.UART_5 = ['SYSCLK', 'PERICKEN1.PECKEN8', 'none', 'SIF5_MODULE'];


NUTOOL_CLOCK.g_unusedModule = {};

NUTOOL_CLOCK.g_equivalentName = [];
NUTOOL_CLOCK.g_equivalentName._S = 'SEL';
NUTOOL_CLOCK.g_equivalentName.OSC10K_EN = 'LRCEN';
NUTOOL_CLOCK.g_equivalentName.OSC22M_EN = 'HRCEN';
NUTOOL_CLOCK.g_equivalentName.XTL32K_EN = 'LXOEN';
NUTOOL_CLOCK.g_equivalentName.XTL12M_EN = 'HXOEN';
NUTOOL_CLOCK.g_equivalentName.HCLK_S = 'SYSCLKSEL';
NUTOOL_CLOCK.g_equivalentName.HCLK_N = 'SYSDIV';
NUTOOL_CLOCK.g_equivalentName.PCLK_S = 'CPUCKDIV';
NUTOOL_CLOCK.g_equivalentName.PWRCON = 'CKCTR';
NUTOOL_CLOCK.g_equivalentName.PLLCON = 'PLLCTR2';
NUTOOL_CLOCK.g_equivalentName.HXT  = 'HXOCLK';
NUTOOL_CLOCK.g_equivalentName.LXT  = 'LXOCLK';
NUTOOL_CLOCK.g_equivalentName.HIRC = 'HRCCLK';
NUTOOL_CLOCK.g_equivalentName.LIRC = 'LRCCLK';
NUTOOL_CLOCK.g_equivalentName.PLL  = 'PLLCLK';
NUTOOL_CLOCK.g_equivalentName.HCLK = 'SYSCLK';
NUTOOL_CLOCK.g_equivalentName.PCLK = 'CPUCLK';
NUTOOL_CLOCK.g_equivalentName.PCLK0 = 'HPCLK';
NUTOOL_CLOCK.g_equivalentName.PCLK1 = 'CPUCLK';
NUTOOL_CLOCK.g_equivalentName.PCLK2 = 'LPCLK';
NUTOOL_CLOCK.g_equivalentName.PCLK0SEL = 'HPCLKSEL';
NUTOOL_CLOCK.g_equivalentName.PCLK1SEL = 'CPUCKDIV';
NUTOOL_CLOCK.g_equivalentName.PCLK2SEL = 'LPCKSEL';
// NUTOOL_CLOCK.g_equivalentName.HXTWAIT  = 'HXOWAIT';

NUTOOL_CLOCK.g_BusNonExistent = ['ADC', 'BUZ', 'CRC', 'DMA0', 'DMA1', 'I2C_6', 'I2C_7', 'I2C_8', 'LIN', 'NF', 'PWM', 'RTC', 'SIF0', 'SIF1', 'SIF2', 'SIF3', 'SIF4', 'SIF5', 'SIF6', 'SIF7', 'SIF8', 'TIMER_8BIT', 'TIMER_8BITL', 'TIMER11_12', 'TIMER13_14', 'TIMER15', 'TIMER7_8', 'TIMER9_10', 'UART_0', 'UART_1', 'UART_2', 'UART_3', 'UART_4', 'UART_5'];
NUTOOL_CLOCK.g_BusFromPCLK1 = [];
NUTOOL_CLOCK.g_DIV_Module_Defines = [];
NUTOOL_CLOCK.g_CPUCLKLimit = 120 * 1000000;
NUTOOL_CLOCK.g_HXTRange = '4~20MHz';
NUTOOL_CLOCK.g_HXTfrequency = 10 * 1000000;
NUTOOL_CLOCK.g_HIRCfrequencyArray = [];
NUTOOL_CLOCK.g_HIRCfrequency = 20 * 1000000;
NUTOOL_CLOCK.g_HIRC2frequencyArray = [];
NUTOOL_CLOCK.g_HIRC2frequency = 0;
NUTOOL_CLOCK.g_HIRC48frequency = 0;
NUTOOL_CLOCK.g_LIRCfrequency = 30 * 1000;
NUTOOL_CLOCK.g_MIRCfrequency = 0;
NUTOOL_CLOCK.g_MIRC1P2Mfrequency = 0;
NUTOOL_CLOCK.g_RTC32kfrequency = 0;
NUTOOL_CLOCK.g_PLL480Mfrequency = 0;
NUTOOL_CLOCK.g_HSUSBOTGPHYfrequency = 0;