NUTOOL_CLOCK.g_cfg_chips = [
    // M2U54
    { name: "M2U54KE4AE", pkg: "LQFP128" },
    { name: "M2U54KG6AE", pkg: "LQFP128" },
    { name: "M2U54YE4AE", pkg: "QFN48" },
    { name: "M2U54YG6AE", pkg: "QFN48" },
    { name: "M2U54SE4AE", pkg: "LQFP64" },
    { name: "M2U54SG6AE", pkg: "LQFP64" },
    { name: "M2U54AE4AE", pkg: "QFN88" },
    { name: "M2U54AG6AE", pkg: "QFN88" },
    // M2U51
    { name: "M2U51YD3AE", pkg: "QFN48" },
    { name: "M2U51YC2AE", pkg: "QFN48" },
    { name: "M2U51TC2AE", pkg: "QFN33" },
    { name: "M2U51FC2AE", pkg: "TSSOP20" },
    { name: "M2U51EC2AE", pkg: "TSSOP28" }
];

NUTOOL_CLOCK.g_register_map = [];
NUTOOL_CLOCK.g_register_map.PWRCTL = ['MIRCFSEL:31-28', 'MIRCEN:26', 'HIRCSTBS:17-16', 'LIRCMSEL:13', 'PDEN:7', 'PDWKIF:6', 'PDWKIEN:5', 'LIRCEN:3', 'HIRCEN:2', 'LXTEN:1'];
NUTOOL_CLOCK.g_register_map.AHBCLK0 = ['GPHCKEN:31', 'GPGCKEN:30', 'GPFCKEN:29', 'GPECKEN:28', 'GPDCKEN:27', 'GPCCKEN:26', 'GPBCKEN:25', 'GPACKEN:24', 'FMCFDIS:23', 'FMCIDLE:15', 'CRPTCKEN:12', 'CRCCKEN:7', 'ISPCKEN:3', 'PDMA0CKEN:2'];
NUTOOL_CLOCK.g_register_map.APBCLK0 = ['ADC0CKEN:28', 'LCDCCKEN:25', 'LCDCKEN:24', 'BPWM0CKEN:23', 'PWM0CKEN:22', 'WWDTCKEN:21', 'USCI0CKEN:20', 'UART2CKEN:18', 'UART1CKEN:17', 'UART0CKEN:16', 'SPI2CKEN:14', 'SPI1CKEN:13', 'SPI0CKEN:12', 'I2C2CKEN:10', 'I2C1CKEN:9', 'I2C0CKEN:8', 'ACMP01CKEN:7', 'CLKOCKEN:6', 'TMR3CKEN:5', 'TMR2CKEN:4', 'TMR1CKEN:3', 'TMR0CKEN:2', 'RTCCKEN:1', 'WDTCKEN:0'];
NUTOOL_CLOCK.g_register_map.CLKSEL0 = ['HCLKSEL:1-0'];
NUTOOL_CLOCK.g_register_map.CLKSEL1 = ['LCDCPSEL:30-29', 'LCDSEL:28', 'ADC0SEL:25-24', 'TMR3SEL:22-20', 'TMR2SEL:18-16', 'TMR1SEL:14-12', 'TMR0SEL:10-8', 'CLKOSEL:6-4', 'WWDTSEL:2-1', 'WDTSEL:0'];
NUTOOL_CLOCK.g_register_map.CLKSEL2 = ['UART2SEL:26-24', 'UART1SEL:22-20', 'UART0SEL:18-16', 'SPI2SEL:9-8', 'SPI1SEL:5-4', 'SPI0SEL:1-0'];
NUTOOL_CLOCK.g_register_map.HCLKDIV = ['HCLKDIV:3-0'];
NUTOOL_CLOCK.g_register_map.PCLKDIV = ['APB1DIV:6-4', 'APB0DIV:2-0'];
NUTOOL_CLOCK.g_register_map.CLKDIV = ['ADC0DIV:23-16', 'UART2DIV:11-8', 'UART1DIV:7-4', 'UART0DIV:3-0'];
NUTOOL_CLOCK.g_register_map.CLKOCTL = ['CLK1HZEN:6', 'DIV1EN:5', 'CLKOEN:4', 'FREQSEL:3-0'];
NUTOOL_CLOCK.g_register_map.RTC_LXTCTL = ['RTCCKSEL:7', 'RTCCKSEL/32768:7'];

NUTOOL_CLOCK.g_register_map_default = [];
NUTOOL_CLOCK.g_register_map_default.PWRCTL = '0x04000018';
NUTOOL_CLOCK.g_register_map_default.AHBCLK0 = '0x00000000';
NUTOOL_CLOCK.g_register_map_default.APBCLK0 = '0x00000000';
NUTOOL_CLOCK.g_register_map_default.CLKSEL0 = '0x00000000';
NUTOOL_CLOCK.g_register_map_default.CLKSEL1 = '0x00000000';
NUTOOL_CLOCK.g_register_map_default.CLKSEL2 = '0x00000000';
NUTOOL_CLOCK.g_register_map_default.HCLKDIV = '0x00000000';
NUTOOL_CLOCK.g_register_map_default.PCLKDIV = '0x00000000';
NUTOOL_CLOCK.g_register_map_default.CLKDIV = '0x00000000';
NUTOOL_CLOCK.g_register_map_default.CLKOCTL = '0x00000000';
NUTOOL_CLOCK.g_register_map_default.RTC_LXTCTL = '0x00000006';

NUTOOL_CLOCK.g_register_map_description = [];
NUTOOL_CLOCK.g_register_map_description.PWRCTL = '0x40000200';
NUTOOL_CLOCK.g_register_map_description.AHBCLK0 = '0x40000204';
NUTOOL_CLOCK.g_register_map_description.APBCLK0 = '0x40000208';
NUTOOL_CLOCK.g_register_map_description.CLKSEL0 = '0x40000210';
NUTOOL_CLOCK.g_register_map_description.CLKSEL1 = '0x40000214';
NUTOOL_CLOCK.g_register_map_description.CLKSEL2 = '0x40000218';
NUTOOL_CLOCK.g_register_map_description.HCLKDIV = '0x40000220';
NUTOOL_CLOCK.g_register_map_description.PCLKDIV = '0x40000224';
NUTOOL_CLOCK.g_register_map_description.CLKDIV = '0x40000228';
NUTOOL_CLOCK.g_register_map_description.CLKOCTL = '0x40000260';
NUTOOL_CLOCK.g_register_map_description.RTC_LXTCTL = '0x40041100';

NUTOOL_CLOCK.g_CLKSEL = [];
NUTOOL_CLOCK.g_CLKSEL.APB1DIV = ['HCLK:0', 'HCLK/2:1', 'HCLK/4:2', 'HCLK/8:3', 'HCLK/16:4'];
NUTOOL_CLOCK.g_CLKSEL.APB0DIV = ['HCLK:0', 'HCLK/2:1', 'HCLK/4:2', 'HCLK/8:3', 'HCLK/16:4'];
NUTOOL_CLOCK.g_CLKSEL.HCLKSEL = ['MIRC:0', 'HIRC:1', 'LIRC:2', 'LXT:3'];
NUTOOL_CLOCK.g_CLKSEL.LCDCPSEL = ['LCDSEL/32:0', 'LCDSEL/16:1', 'LCDSEL/8:2'];
NUTOOL_CLOCK.g_CLKSEL.LCDSEL = ['LIRC:0', 'LXT:1'];  
NUTOOL_CLOCK.g_CLKSEL.ADC0SEL = ['PCLK1:0', 'MIRC:1', 'HIRC:2'];  
NUTOOL_CLOCK.g_CLKSEL.TMR3SEL = ['PCLK1:0', 'MIRC:1', 'HIRC:2', 'LIRC:3', 'LXT:4', 'EXT:5'];  
NUTOOL_CLOCK.g_CLKSEL.TMR2SEL = ['PCLK1:0', 'MIRC:1', 'HIRC:2', 'LIRC:3', 'LXT:4', 'EXT:5'];  
NUTOOL_CLOCK.g_CLKSEL.TMR1SEL = ['PCLK0:0', 'MIRC:1', 'HIRC:2', 'LIRC:3', 'LXT:4', 'EXT:5'];  
NUTOOL_CLOCK.g_CLKSEL.TMR0SEL = ['PCLK0:0', 'MIRC:1', 'HIRC:2', 'LIRC:3', 'LXT:4', 'EXT:5'];  
NUTOOL_CLOCK.g_CLKSEL.CLKOSEL = ['HCLK:0', 'MIRC:1', 'HIRC:2', 'LIRC:3', 'LXT:4'];  
NUTOOL_CLOCK.g_CLKSEL.WWDTSEL = ['LIRC:0', 'LXT:1'];  
NUTOOL_CLOCK.g_CLKSEL.WDTSEL = ['LIRC:0', 'LXT:1'];  
NUTOOL_CLOCK.g_CLKSEL.UART2SEL = ['PCLK0:0', 'MIRC:1', 'HIRC:2', 'LIRC:3', 'LXT:4'];  
NUTOOL_CLOCK.g_CLKSEL.UART1SEL = ['PCLK1:0', 'MIRC:1', 'HIRC:2', 'LIRC:3', 'LXT:4'];  
NUTOOL_CLOCK.g_CLKSEL.UART0SEL = ['PCLK0:0', 'MIRC:1', 'HIRC:2', 'LIRC:3', 'LXT:4'];  
NUTOOL_CLOCK.g_CLKSEL.SPI2SEL = ['PCLK1:0', 'MIRC:1', 'HIRC:2'];  
NUTOOL_CLOCK.g_CLKSEL.SPI1SEL = ['PCLK0:0', 'MIRC:1', 'HIRC:2'];  
NUTOOL_CLOCK.g_CLKSEL.SPI0SEL = ['PCLK1:0', 'MIRC:1', 'HIRC:2'];
NUTOOL_CLOCK.g_CLKSEL.RTCCKSEL = ['LXT:0', 'LIRC:1'];
NUTOOL_CLOCK.g_CLKSEL['RTCCKSEL/32768'] = ['LXT/32768:0', 'LIRC/32768:1'];

NUTOOL_CLOCK.g_CLKSEL_EXTENDED = [];

NUTOOL_CLOCK.g_Module = [];
NUTOOL_CLOCK.g_Module.ACMP01 = ['PCLK1', 'ACMP01CKEN', 'none'];
NUTOOL_CLOCK.g_Module.ADC0 = ['ADC0SEL', 'ADC0CKEN', 'ADC0DIV'];
NUTOOL_CLOCK.g_Module.BPWM0 = ['PCLK0', 'BPWM0CKEN', 'none'];
NUTOOL_CLOCK.g_Module.CRC = ['HCLK', 'CRCCKEN', 'none'];
NUTOOL_CLOCK.g_Module.CRPT = ['HCLK', 'CRPTCKEN', 'none'];
NUTOOL_CLOCK.g_Module.GPA = ['HCLK', 'GPACKEN', 'none'];
NUTOOL_CLOCK.g_Module.GPB = ['HCLK', 'GPBCKEN', 'none'];
NUTOOL_CLOCK.g_Module.GPC = ['HCLK', 'GPCCKEN', 'none'];
NUTOOL_CLOCK.g_Module.GPD = ['HCLK', 'GPDCKEN', 'none'];
NUTOOL_CLOCK.g_Module.GPE = ['HCLK', 'GPECKEN', 'none'];
NUTOOL_CLOCK.g_Module.GPF = ['HCLK', 'GPFCKEN', 'none'];
NUTOOL_CLOCK.g_Module.GPG = ['HCLK', 'GPGCKEN', 'none'];
NUTOOL_CLOCK.g_Module.GPH = ['HCLK', 'GPHCKEN', 'none'];
NUTOOL_CLOCK.g_Module.I2C0 = ['PCLK0', 'I2C0CKEN', 'none'];
NUTOOL_CLOCK.g_Module.I2C1 = ['PCLK1', 'I2C1CKEN', 'none'];
NUTOOL_CLOCK.g_Module.I2C2 = ['PCLK0', 'I2C2CKEN', 'none'];
NUTOOL_CLOCK.g_Module.ISP = ['HCLK', 'ISPCKEN', 'none'];
NUTOOL_CLOCK.g_Module.LCD = ['LCDSEL', 'LCDCKEN', 'none'];
NUTOOL_CLOCK.g_Module.LCDCP = ['LCDCPSEL', 'LCDCCKEN', 'none'];
NUTOOL_CLOCK.g_Module.PDMA0 = ['HCLK', 'PDMA0CKEN', 'none'];
NUTOOL_CLOCK.g_Module.PWM0 = ['PCLK0', 'PWM0CKEN', 'none'];
NUTOOL_CLOCK.g_Module.RTC = ['RTCCKSEL', 'RTCCKEN', 'none'];
NUTOOL_CLOCK.g_Module.SPI0 = ['SPI0SEL', 'SPI0CKEN', 'none'];
NUTOOL_CLOCK.g_Module.SPI1 = ['SPI1SEL', 'SPI1CKEN', 'none'];
NUTOOL_CLOCK.g_Module.SPI2 = ['SPI2SEL', 'SPI2CKEN', 'none'];
NUTOOL_CLOCK.g_Module.TMR0 = ['TMR0SEL', 'TMR0CKEN', 'none'];
NUTOOL_CLOCK.g_Module.TMR1 = ['TMR1SEL', 'TMR1CKEN', 'none'];
NUTOOL_CLOCK.g_Module.TMR2 = ['TMR2SEL', 'TMR2CKEN', 'none'];
NUTOOL_CLOCK.g_Module.TMR3 = ['TMR3SEL', 'TMR3CKEN', 'none'];
NUTOOL_CLOCK.g_Module.UART0 = ['UART0SEL', 'UART0CKEN', 'UART0DIV'];
NUTOOL_CLOCK.g_Module.UART1 = ['UART1SEL', 'UART1CKEN', 'UART1DIV'];
NUTOOL_CLOCK.g_Module.UART2 = ['UART2SEL', 'UART2CKEN', 'UART2DIV'];
NUTOOL_CLOCK.g_Module.USCI0 = ['PCLK0', 'USCI0CKEN', 'none'];
NUTOOL_CLOCK.g_Module.WDT = ['WWDTSEL', 'WDTCKEN', 'none'];
NUTOOL_CLOCK.g_Module.WWDT = ['WDTSEL', 'WWDTCKEN', 'none'];
NUTOOL_CLOCK.g_Module.CLKO = ['CLKOSEL', 'CLKOCKEN/CLKOEN/!DIV1EN/!CLK1HZEN', 'none'];
NUTOOL_CLOCK.g_Module.CLKO_1Hz = ['RTCCKSEL/32768', 'CLK1HZEN', 'none'];
NUTOOL_CLOCK.g_Module.CLKO_Divider = ['CLKOSEL', 'CLKOCKEN/CLKOEN/DIV1EN/!CLK1HZEN', 'FREQSEL'];

NUTOOL_CLOCK.g_unusedModule = {
    'M2U54KE4AE': [],
    'M2U54KG6AE': [],
    'M2U54YE4AE': [],
    'M2U54YG6AE': [],
    'M2U54SE4AE': [],
    'M2U54SG6AE': [],
    'M2U54AE4AE': [],
    'M2U54AG6AE': [],
    'M2U51YD3AE': ['LCD', 'LCDCP'],
    'M2U51YC2AE': ['I2C2', 'UART2', 'SPI1', 'SPI2', 'LCD', 'LCDCP', 'PWM0', 'USCI0', 'ACMP01'],
    'M2U51TC2AE': ['I2C2', 'UART2', 'SPI1', 'SPI2', 'LCD', 'LCDCP', 'PWM0', 'USCI0', 'ACMP01'],
    'M2U51FC2AE': ['I2C2', 'UART2', 'SPI1', 'SPI2', 'LCD', 'LCDCP', 'PWM0', 'USCI0', 'ACMP01'],
    'M2U51EC2AE': ['I2C2', 'UART2', 'SPI1', 'SPI2', 'LCD', 'LCDCP', 'PWM0', 'USCI0', 'ACMP01']
};

NUTOOL_CLOCK.g_equivalentName = [];
NUTOOL_CLOCK.g_equivalentName._S = 'SEL';
NUTOOL_CLOCK.g_equivalentName.OSC10K_EN = 'LIRCEN';
NUTOOL_CLOCK.g_equivalentName.OSC22M_EN = 'HIRCEN';
NUTOOL_CLOCK.g_equivalentName.XTL32K_EN = 'LXTEN';
NUTOOL_CLOCK.g_equivalentName.WDT_EN = 'WDTCKEN';
NUTOOL_CLOCK.g_equivalentName.HCLK_S = 'HCLKSEL';
NUTOOL_CLOCK.g_equivalentName.HCLK_N = 'HCLKDIV';
NUTOOL_CLOCK.g_equivalentName.PWRCON = 'PWRCTL';
NUTOOL_CLOCK.g_equivalentName.PCLK0SEL = 'APB0DIV';
NUTOOL_CLOCK.g_equivalentName.PCLK1SEL = 'APB1DIV';

NUTOOL_CLOCK.g_BusNonExistent = [];
NUTOOL_CLOCK.g_BusFromPCLK1 = ['ACMP01', 'ADC0', 'I2C1', 'LCD', 'LCDCP', 'RTC', 'SPI0', 'SPI2', 'TMR2', 'TMR3', 'UART1'];
NUTOOL_CLOCK.g_DIV_Module_Defines = [];
NUTOOL_CLOCK.g_CPUCLKLimit = 40 * 1000000;
NUTOOL_CLOCK.g_HXTRange = '4~24MHz';
NUTOOL_CLOCK.g_HXTfrequency = 0;
NUTOOL_CLOCK.g_HIRCfrequencyArray = [];
NUTOOL_CLOCK.g_HIRCfrequency = 16 * 1000000;
NUTOOL_CLOCK.g_HIRC2frequencyArray = [];
NUTOOL_CLOCK.g_HIRC2frequency = 0;
NUTOOL_CLOCK.g_HIRC48frequency = 0;
NUTOOL_CLOCK.g_LIRCfrequency = 38.4 * 1000;
NUTOOL_CLOCK.g_MIRCfrequency = 1000000;
NUTOOL_CLOCK.g_MIRCfreeuncyArray = [1000000, 2000000, 4000000, 8000000, 12000000, 16000000, 24000000, 32000000, 40000000];
NUTOOL_CLOCK.g_MIRC1P2Mfrequency = 0;
NUTOOL_CLOCK.g_RTC32kfrequency = 0;
NUTOOL_CLOCK.g_PLL480Mfrequency = 0;
NUTOOL_CLOCK.g_HSUSBOTGPHYfrequency = 0;
